### PR TITLE
Adding Transaction handling and connection to API

### PR DESCRIPTION
**Pull request by Russelldan554**
This update adds functionality to the transaction cards to add and get real data from the API. May update later with filter for search but this might be done on the backend...

### CODE REVIEW

**Review by CrutchTheClutch — CHANGES_REQUESTED** [review]
This pr adds compile errors to at least two files (AddTransactionCard.jsx, API.jsx).  The specific error I am met with at compile is:
```javascript
Failed to compile.

./src/Components/Transactions/AddTransactionCard.jsx
Attempted import error: 'addTransaction' is not exported from '../../Components/API' (imported as 'API').
```

**Comment by CrutchTheClutch** [comment]
This pr aims to resolve #12

**Comment by CrutchTheClutch** [comment]
This pr aims to resolve #12

**Comment by Russelldan554** [comment]
Changes have been made everything is merged properly.

**Review by CrutchTheClutch — APPROVED** [review]

**Pull request merged**
